### ISSUE TITLE
Missing object states (when managing policy limitations)

### ISSUE THREAD

**Issue by xrow** [kaliop-uk/ezmigrationbundle#122] opened 2017-09-04 12:36 UTC
Hi,

I have seen that there is not yet support for object states. I might implement it myself if it bothers me too much. This is for now just a reminder. 

https://github.com/kaliop-uk/ezmigrationbundle/blob/master/Core/Helper/LimitationConverter.php

**Comment by gggeek** [comment] 2017-09-04 12:40
As in: missing CRUD of Object States?

It seems that the ContentManager can already assign them, and we can use them as well for matching...

**Comment by xrow** [comment] 2017-09-04 13:23
CRUD has the object states.

https://github.com/kaliop-uk/ezmigrationbundle/blob/master/Core/Helper/LimitationConverter.php#L123

I am seeing your have a default case, but amybe that is no goto for obejct state limitations. I need to check a bit more.

**Comment by gggeek** [comment] 2017-09-19 19:00
Any news on your side ?

**Comment by xrow** [comment] 2017-09-20 08:32
Not yet ... Backlog...

**Comment by gggeek** [comment] 2017-09-27 22:34
Note: I added a test for checking that setting the obj state works, and it seem to work as intended:

https://github.com/kaliop-uk/ezmigrationbundle/commit/904f1f19c39b9b34cc19ce7e6d4d5d146bd6e92e

**Comment by gggeek** [comment] 2020-10-30 14:51
Ping

**Comment by gggeek** [comment] 2022-10-13 14:05
Long time open with no feedback. Closing

**Closed by gggeek** 2022-10-13 14:05 UTC
Labels: bug, waiting for feedback
