### ISSUE TITLE
netgen/tagsbundle subTreeLimit migration aborted

### ISSUE THREAD

**Issue by volarname** [kaliop-uk/ezmigrationbundle#109] opened 2017-03-10 10:48 UTC
when using "netgen/tagsbundle": "3.0.0-rc1"
the following migration
```
-
    mode: update
    type: content_type
    lang: slk-SK
    identifier: article
    attributes:
        -
            identifier: keywords
            type: eztags
            validator-configuration:
                TagsValueValidator: { subTreeLimit: 2 }
```

will fail with error:

```
Processing 20170303111827_content_type_update-article-keywords-internal-tags.yml

Migration aborted! Reason: Error in execution of step 1: ContentType FieldDefinitions did not validate
Setting "%setting%" is unknown - array (
  '%setting%' => 'subTreeLimit',
)
Setting "%setting%" is unknown - array (
  '%setting%' => 'maxTags',
) in file /app/vendor/ezsystems/ezpublish-kernel/eZ/Publish/Core/Repository/Helper/ContentTypeDomainMapper.php line 285
```

**Comment by gggeek** [comment] 2017-03-14 00:02
Hello.

I tried to reproduce this, but I am at a loss for the moment:
- installed ezplatform 1.8
- installed eztagsbundle 3.0
- tried to create a content type with a tags field using a migration, and I get the error `value must be an existing tag ID`
- but I can not find any panel in the admin interface to manage the tags, as was possible in eZ5 ?

**Comment by gggeek** [comment] 2017-03-14 00:11
ps: I managed to reset the admin interface.
But I still cant reproduce the error.

These are the 2 migrations I executed:
```
-
    mode: create
    type: content_type
    content_type_group: Content
    name_pattern: '<title>'
    identifier: testcontent
    name: TestContent
    attributes:
        -
            identifier: title
            type: ezstring
        -
            identifier: keywords
            type: eztags

-
    mode: update
    type: content_type
    match:
        identifier: testcontent
    attributes:
        -
            identifier: keywords
            type: eztags
            validator-configuration:
                TagsValueValidator: { subTreeLimit: 1 }
```

**Comment by gggeek** [comment] 2017-03-14 00:13
Did you upgrade by any chance the version of the tagsbundle after having some content class with tag fields already defined?

**Comment by gggeek** [comment] 2018-05-15 17:42
Note: seems that this bug does happen when using ezplatform 2 - the recent Travis test runs confirm it.
That will give me another chance to investigate...

**Comment by gggeek** [comment] 2018-05-15 20:41
Note: seems that this bug does happen when using ezplatform 2 - the recent Travis test runs confirm it.
That will give me another chance to investigate...

**Comment by gggeek** [comment] 2018-07-17 08:41
OK, so what we found out with  ezplatform 2 is that validation problems do happen when you are loading the TagsBundle bundle _before_ the eZ kernel bundles in appKernel.php. Switching to load the TagsBundle last solved the problems that we had with Travis tests...

**Comment by gggeek** [comment] 2018-08-06 10:38
Ping any feedback ?

**Comment by emodric** [comment] 2018-08-06 10:41
@gggeek What kind of feedback do you need? :)

**Comment by yoyolepsy** [comment] 2018-11-12 17:01
Hello,

Sorry if my feedback is late.
Here my last feedback. We have had a similar issue when we try to update from eZPlatform 1.10 to eZPltaform 2.2.
When we have changed the order of TagsBundle in AppKernel.php as proposed by @gggeek , it has been good for us.

**Comment by gggeek** [comment] 2018-11-12 18:11
Thx. Will then close the issue. If there are still problems, please open another one.

**Closed by gggeek** 2018-11-12 18:11 UTC
Labels: bug
