### ISSUE TITLE
Cannot remove ezimage field from article content type

### ISSUE THREAD

**Issue by phalasz** [kaliop-uk/ezmigrationbundle#6] opened 2016-03-23 15:11 UTC
Hello,

On a standard eZ Platform and eZ Studio install with the demo content trying to remove the image attribute from the Article content type the migration exits with the following error:

> Error "At least one element is required as value."

All other attributes can be removed without any issues.

Content of the migration yml file.

```
 -
    mode: update
    type: content_type
    identifier: article
    remove_attributes: ["image"]
```

If you need any more info please let me know.

**Comment by DeClemo** [comment] 2016-03-24 09:58
@phalasz I will look into this over the weekend and hopefully have a fix for it then. :-)

**Comment by phalasz** [comment] 2016-03-24 10:28
Thank you. Looks to be a weird one.

**Comment by gggeek** [comment] 2016-08-22 12:10
I added a test for removing an image attribute from a custom calss in the upcoming2.0, and it works.

I did not try with the stock ezdemo article class though. I will give that a spin before closing this issue.

**Comment by gggeek** [comment] 2017-03-01 00:19
Closing as can't reproduce. Please reopen if this happens again...

**Closed by gggeek** 2017-03-01 00:19 UTC
Labels: bug
