### ISSUE TITLE
Unable to use the location remote id in location update migration

### ISSUE THREAD

**Issue by jbcr** [kaliop-uk/ezmigrationbundle#216] opened 2019-07-31 15:57 UTC
For move namy contents, I use a migration in mode `update` with the type `location`. But I need use the location remote id for locate the new parent location (`parent_location`).

This bundle work in fact only with the location id or by reference.
But the [documentation](https://github.com/kaliop-uk/ezmigrationbundle/blob/master/Resources/doc/DSL/Locations.yml#L111) indicates that it is possible to use the remote Id.

**Comment by gggeek** [comment] 2019-07-31 16:14
I think I have found the cause of this.

Could you try changing line 187 in LocationManager.php from

```$newParentLocation = $locationService->loadLocation($parentLocationId);```

to

```$newParentLocation = $this->matchLocationByKey($parentLocationId);```

and see if it works?

**Comment by jbcr** [comment] 2019-08-01 05:39
The new line `$newParentLocation = $this->matchLocationByKey($parentLocationId);` work fine.

**Comment by gggeek** [comment] 2019-08-01 08:28
Fixed in 5.10.1

**Closed** 2019-08-01 08:27 UTC
Labels: bug
